### PR TITLE
WIP: Add support for Xen xl command

### PR DESCRIPTION
**Pull request by guillaumelecerf**
I have to admit that I am a Perl newbie, but here is a WIP of the implementation of the new xl command from Xen 4.4, superseding the xm one.

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi,

Thanks you for your contribution.
We will make some take on your module and merge it if everything work fine.

However, that might  take sometime because we do not have any platform to test Xen at the moment.

Regards,
Gilles Dubois.

**Comment by guillaumelecerf** [comment]
My changes already merged ?? https://github.com/OCSInventory-NG/UnixAgent/commit/5213079fd2b597873f3f8190630724986fed8e76 ?

**Comment by gillesdubois** [comment]
Hi,

Your changes as been merged with the master branch of the unix agent.

Thanks you very much for your contribution you will be mark as a contributor of the Unix Agent when the new version will be released :)

Regards,
Gilles Dubois.

**Comment by guillaumelecerf** [comment]
Unfortunately, you took my code wrongly, hence #26.

**Pull request closed without merging**
