### PR TITLE
disk and video card fix if lshw and nvidia-smi present

### PR DESCRIPTION
**Pull request by jpisard**
Fix getFromLshw XML nodes ( lib/Ocsinventory/Agent/Backend/OS/Linux/Storages.pm )
   disk not in inventory if lshw present :

   my $nodes = $data->{list}->{node} represent node and not nodeslist

Fix nvidia card not present if nvidia-smi is detected  ( lib/Ocsinventory/Agent/Backend/OS/Generic/Lspci/Videos.pm )

### CODE REVIEW

**Comment by fbomj** [comment]
Hi,

Could you explain the problem you had before the correction ?

Regards

**Comment by jpisard** [comment]
disk not in inventory if lshw  present  :

my $nodes = $data->{list}->{node} represent node and not nodeslist

**Comment by jpisard** [comment]
nvidia card not present if nvidia-smi is detected

because the perl script need nvidia::ml module that could'nt be installed (need perl 5.10 for gcc compatibility)

**Comment by fbomj** [comment]
which version of the agent and on which distro have you tested?

**Comment by jpisard** [comment]
tested on agent 2.4.2 (code is the same in 2.6.0)
tested on Ubuntu Xenial and Debian Stretch

**Comment by fbomj** [comment]
Hi,
Thanks for your PR.
Regards

**Pull request merged**
